[package]
name = "openfga_idl_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openfga_common = { path = "../openfga_common"}
chumsky = "0.8.0"